/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:49:02 GMT 2023
 */

package net.kencochrane.a4j.DAO;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import net.kencochrane.a4j.DAO.Search;
import net.kencochrane.a4j.beans.BlendedSearch;
import net.kencochrane.a4j.beans.ProductInfo;
import net.kencochrane.a4j.beans.SellerSearch;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Search_ESTest extends Search_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Search search0 = new Search();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/S__,C|#NCH2{.XML");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      // Undeclared exception!
      try { 
        search0.SimilaritesSearch("_,C|#NCh2{", (String) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/wutka/jox/JOXBeanInputStream
         //
         verifyException("net.kencochrane.a4j.DAO.Search", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Search search0 = new Search();
      ProductInfo productInfo0 = search0.SimilaritesSearch("X", "X");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Search search0 = new Search();
      SellerSearch sellerSearch0 = search0.ThirdParty("jKXS43k/Tsf^{M_", "jKXS43k/Tsf^{M_", "jKXS43k/Tsf^{M_", "jKXS43k/Tsf^{M_");
      assertNull(sellerSearch0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Search search0 = new Search();
      ProductInfo productInfo0 = search0.Keyword("jKXS43k/Tsf^{M_", "jKXS43k/Tsf^{M_", "jKXS43k/Tsf^{M_", "jKXS43k/Tsf^{M_");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Search search0 = new Search();
      BlendedSearch blendedSearch0 = search0.Blended("BsuzsI8", "BsuzsI8");
      assertNull(blendedSearch0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Search search0 = new Search();
      ProductInfo productInfo0 = search0.UpcSearch("", "", "]^Y][yn+4rlgZAO");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Search search0 = new Search();
      ProductInfo productInfo0 = search0.ListmaniaSearch("LX.1a'JI%t`Zv");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Search search0 = new Search();
      ProductInfo productInfo0 = search0.ArtistSearch("", "", "");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Search search0 = new Search();
      ProductInfo productInfo0 = search0.AuthorSearch("_,C|#NCh2{", "?uY>MCl$A$O+QNA");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Search search0 = new Search();
      ProductInfo productInfo0 = search0.DirectorSearch("q<!2i>LAmMArC@=*Ag", "q<!2i>LAmMArC@=*Ag", "q<!2i>LAmMArC@=*Ag");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Search search0 = new Search();
      ProductInfo productInfo0 = search0.ManufactureSearch("", "", "");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Search search0 = new Search();
      ProductInfo productInfo0 = search0.ActorSearch("lite", "lite", "lite");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Search search0 = new Search();
      ProductInfo productInfo0 = search0.WishListSearch("n9=|");
      assertNull(productInfo0);
  }
}
