/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:11:26 GMT 2023
 */

package net.kencochrane.a4j.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import net.kencochrane.a4j.util.a4jUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class a4jUtil_ESTest extends a4jUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      a4jUtil a4jUtil0 = new a4jUtil();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      arrayList0.add("URLSeperator");
      arrayList0.add("Yi4~)");
      String string0 = a4jUtil0.arrayToCommaString(arrayList0);
      assertEquals("URLSeperator, Yi4~)", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      a4jUtil a4jUtil0 = new a4jUtil();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      arrayList0.add((Integer) null);
      String string0 = a4jUtil0.arrayToCommaString(arrayList0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      a4jUtil a4jUtil0 = new a4jUtil();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      String string0 = a4jUtil0.arrayToCommaString(arrayList0);
      assertFalse(arrayList0.contains(string0));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      a4jUtil a4jUtil0 = new a4jUtil();
      String string0 = a4jUtil0.arrayToCommaString((ArrayList) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      a4jUtil a4jUtil0 = new a4jUtil();
      String string0 = a4jUtil0.URLFriendlyName("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      a4jUtil a4jUtil0 = new a4jUtil();
      String string0 = a4jUtil0.dencodeString("URLSeperator");
      assertEquals("URLSeperator", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      a4jUtil a4jUtil0 = new a4jUtil();
      String string0 = a4jUtil0.encodeString("Y3}^3");
      assertEquals("Y3%7D%5E3", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      a4jUtil a4jUtil0 = new a4jUtil();
      BigDecimal bigDecimal0 = a4jUtil0.getPrice("D?,zZQoy0");
      assertEquals((byte)0, bigDecimal0.byteValue());
  }
}
