/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:11:14 GMT 2023
 */

package net.kencochrane.a4j.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Properties;
import net.kencochrane.a4j.util.LoadProperties;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LoadProperties_ESTest extends LoadProperties_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LoadProperties loadProperties0 = LoadProperties.instance();
      LoadProperties loadProperties1 = LoadProperties.instance();
      assertSame(loadProperties1, loadProperties0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LoadProperties loadProperties0 = LoadProperties.instance();
      Properties properties0 = loadProperties0.getProperties();
      assertFalse(properties0.isEmpty());
  }
}
