/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:50:11 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.Accessories;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Accessories_ESTest extends Accessories_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Accessories accessories0 = new Accessories();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      arrayList0.add((Object) accessories0);
      accessories0.accessory = arrayList0;
      String string0 = accessories0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Accessories accessories0 = new Accessories();
      String[] stringArray0 = new String[0];
      accessories0.setAccessory(stringArray0);
      String string0 = accessories0.toString();
      assertEquals("Accessories is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Accessories accessories0 = new Accessories();
      String[] stringArray0 = new String[3];
      accessories0.setAccessory(stringArray0);
      // Undeclared exception!
      try { 
        accessories0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Accessories accessories0 = new Accessories();
      String string0 = accessories0.toString();
      assertEquals("Accessories is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Accessories accessories0 = new Accessories();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      accessories0.accessory = arrayList0;
      // Undeclared exception!
      try { 
        accessories0.getAccessory(688);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 688, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Accessories accessories0 = new Accessories();
      String[] stringArray0 = new String[3];
      accessories0.setAccessory(stringArray0);
      String string0 = accessories0.getAccessory((-105));
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Accessories accessories0 = new Accessories();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      arrayList0.add((Object) accessories0);
      accessories0.accessory = arrayList0;
      // Undeclared exception!
      try { 
        accessories0.getAccessory();
        fail("Expecting exception: ArrayStoreException");
      
      } catch(ArrayStoreException e) {
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Accessories accessories0 = new Accessories();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      accessories0.accessory = arrayList0;
      String[] stringArray0 = accessories0.getAccessory();
      accessories0.setAccessory(stringArray0);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Accessories accessories0 = new Accessories();
      ArrayList arrayList0 = accessories0.getAccessoryArray();
      assertNull(arrayList0);
  }
}
