/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:51:19 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.Artists;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Artists_ESTest extends Artists_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Artists artists0 = new Artists();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      artists0.artists = arrayList0;
      Integer integer0 = new Integer(1);
      arrayList0.add(integer0);
      String string0 = artists0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Artists artists0 = new Artists();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      artists0.artists = arrayList0;
      String string0 = artists0.toString();
      assertEquals("artists is null or size 0 \n", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Artists artists0 = new Artists();
      String string0 = artists0.toString();
      assertEquals("artists is null or size 0 \n", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Artists artists0 = new Artists();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      artists0.artists = arrayList0;
      // Undeclared exception!
      try { 
        artists0.getArtist(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Artists artists0 = new Artists();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      artists0.artists = arrayList0;
      String string0 = artists0.getArtist((-1));
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Artists artists0 = new Artists();
      String[] stringArray0 = new String[1];
      artists0.setArtist(stringArray0);
      String[] stringArray1 = artists0.getArtist();
      assertEquals(1, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Artists artists0 = new Artists();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      artists0.artists = arrayList0;
      String[] stringArray0 = artists0.getArtist();
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Artists artists0 = new Artists();
      ArrayList arrayList0 = artists0.getArtistsArray();
      assertNull(arrayList0);
  }
}
