/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:52:28 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.Authors;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Authors_ESTest extends Authors_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Authors authors0 = new Authors();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      Integer integer0 = new Integer(0);
      arrayList0.add(integer0);
      authors0.author = arrayList0;
      String string0 = authors0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Authors authors0 = new Authors();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      authors0.author = arrayList0;
      String string0 = authors0.toString();
      assertEquals("Authors is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Authors authors0 = new Authors();
      String string0 = authors0.toString();
      assertEquals("Authors is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Authors authors0 = new Authors();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      authors0.author = arrayList0;
      // Undeclared exception!
      try { 
        authors0.getAuthor(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Authors authors0 = new Authors();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      authors0.author = arrayList0;
      String string0 = authors0.getAuthor((-1));
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Authors authors0 = new Authors();
      String[] stringArray0 = new String[1];
      authors0.setAuthor(stringArray0);
      String[] stringArray1 = authors0.getAuthor();
      assertEquals(1, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Authors authors0 = new Authors();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      authors0.author = arrayList0;
      String[] stringArray0 = authors0.getAuthor();
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Authors authors0 = new Authors();
      ArrayList arrayList0 = authors0.getAuthorsArray();
      assertNull(arrayList0);
  }
}
