/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:52:51 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.BrowseList;
import net.kencochrane.a4j.beans.BrowseNode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BrowseList_ESTest extends BrowseList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BrowseList browseList0 = new BrowseList();
      BrowseNode[] browseNodeArray0 = new BrowseNode[5];
      BrowseNode browseNode0 = new BrowseNode();
      browseNodeArray0[1] = browseNode0;
      browseList0.setBrowseNode(browseNodeArray0);
      String string0 = browseList0.toString();
      assertEquals("# of nodes = 5\nName: null\nID: null\n", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BrowseList browseList0 = new BrowseList();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      browseList0.nodes = arrayList0;
      String string0 = browseList0.toString();
      assertEquals("No nodes\n", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BrowseList browseList0 = new BrowseList();
      String string0 = browseList0.toString();
      assertEquals("No nodes\n", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      BrowseList browseList0 = new BrowseList();
      // Undeclared exception!
      try { 
        browseList0.getBrowseNode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.kencochrane.a4j.beans.BrowseList", e);
      }
  }
}
