/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:53:05 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.BrowseNode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BrowseNode_ESTest extends BrowseNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      browseNode0.addSubNode(browseNode0);
      browseNode0.printNode();
      assertNull(browseNode0.getBrowseName());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      browseNode0.printNode();
      assertNull(browseNode0.getBrowseId());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      browseNode0.setSubNodes((ArrayList) null);
      browseNode0.printNode();
      assertNull(browseNode0.getBrowseName());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      browseNode0.addSubNode(browseNode0);
      browseNode0.setBrowseId("");
      BrowseNode browseNode1 = browseNode0.getSubNode(" - ");
      assertNull(browseNode1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      BrowseNode browseNode1 = browseNode0.getSubNode("");
      assertNull(browseNode1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      browseNode0.setSubNodes((ArrayList) null);
      BrowseNode browseNode1 = browseNode0.getSubNode("");
      assertNull(browseNode1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      browseNode0.setMode("");
      assertNull(browseNode0.getBrowseName());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      browseNode0.setBrowseName("");
      assertNull(browseNode0.getBrowseId());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      ArrayList arrayList0 = browseNode0.getParentNodes();
      browseNode0.setSubNodes(arrayList0);
      assertNull(browseNode0.getBrowseId());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      browseNode0.setBrowseId("");
      browseNode0.addSubNode(browseNode0);
      BrowseNode browseNode1 = browseNode0.getSubNode("");
      assertSame(browseNode0, browseNode1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      ArrayList arrayList0 = browseNode0.getSubNodes();
      assertTrue(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      String string0 = browseNode0.toString();
      assertEquals("null - null -- null", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      browseNode0.setParentNodes(arrayList0);
      assertNull(browseNode0.getBrowseId());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BrowseNode browseNode0 = new BrowseNode();
      String string0 = browseNode0.getMode();
      assertNull(string0);
  }
}
