/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:54:23 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.Directors;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Directors_ESTest extends Directors_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Directors directors0 = new Directors();
      String[] stringArray0 = new String[2];
      stringArray0[0] = "WrOWNm";
      stringArray0[1] = "\"1OiWJ'Nyr<V$||/";
      directors0.setDirector(stringArray0);
      String string0 = directors0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Directors directors0 = new Directors();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      directors0.directors = arrayList0;
      String string0 = directors0.toString();
      assertEquals("Director is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Directors directors0 = new Directors();
      String string0 = directors0.toString();
      assertEquals("Director is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Directors directors0 = new Directors();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      directors0.directors = arrayList0;
      // Undeclared exception!
      try { 
        directors0.getDirector(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Directors directors0 = new Directors();
      String[] stringArray0 = new String[5];
      directors0.setDirector(stringArray0);
      String string0 = directors0.getDirector(0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Directors directors0 = new Directors();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      Object object0 = new Object();
      arrayList0.add(object0);
      ArrayList<Object> arrayList1 = new ArrayList<Object>();
      directors0.directors = arrayList1;
      directors0.directors = arrayList0;
      // Undeclared exception!
      try { 
        directors0.getDirector();
        fail("Expecting exception: ArrayStoreException");
      
      } catch(ArrayStoreException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Directors directors0 = new Directors();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      directors0.directors = arrayList0;
      String[] stringArray0 = directors0.getDirector();
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Directors directors0 = new Directors();
      ArrayList arrayList0 = directors0.getDirectorsArray();
      assertNull(arrayList0);
  }
}
