/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:55:33 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.Features;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Features_ESTest extends Features_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Features features0 = new Features();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "Feature is null or size 0\n";
      features0.setFeature(stringArray0);
      String string0 = features0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Features features0 = new Features();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      features0.features = arrayList0;
      String string0 = features0.toString();
      assertEquals("Feature is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Features features0 = new Features();
      String string0 = features0.toString();
      assertEquals("Feature is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Features features0 = new Features();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      features0.features = arrayList0;
      // Undeclared exception!
      try { 
        features0.getFeature(779);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 779, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Features features0 = new Features();
      String[] stringArray0 = new String[1];
      features0.setFeature(stringArray0);
      String string0 = features0.getFeature((-46));
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Features features0 = new Features();
      String[] stringArray0 = new String[1];
      features0.setFeature(stringArray0);
      String[] stringArray1 = features0.getFeature();
      assertEquals(1, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Features features0 = new Features();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      features0.features = arrayList0;
      String[] stringArray0 = features0.getFeature();
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Features features0 = new Features();
      ArrayList arrayList0 = features0.getFeaturesArray();
      assertNull(arrayList0);
  }
}
