/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:56:20 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import net.kencochrane.a4j.beans.Item;
import net.kencochrane.a4j.beans.Items;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Items_ESTest extends Items_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Items items0 = new Items();
      Item[] itemArray0 = new Item[1];
      Item item0 = new Item();
      itemArray0[0] = item0;
      items0.setItem(itemArray0);
      String string0 = items0.toString();
      assertEquals("Asin = null\nName = null\nquantity = null\n", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Items items0 = new Items();
      items0.items = null;
      String string0 = items0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Items items0 = new Items();
      Item[] itemArray0 = new Item[1];
      items0.setItem(itemArray0);
      String string0 = items0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Items items0 = new Items();
      String string0 = items0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Items items0 = new Items();
      Item[] itemArray0 = items0.getItem();
      items0.setItem(itemArray0);
      assertEquals(0, itemArray0.length);
  }
}
