/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:56:09 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import net.kencochrane.a4j.beans.Item;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Item_ESTest extends Item_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Item item0 = new Item();
      item0.setQuantity("BgxJLzFR;ZI&");
      assertNull(item0.getExchangeId());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getMerchantSku();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Item item0 = new Item();
      item0.setAsin((String) null);
      assertNull(item0.getProductName());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Item item0 = new Item();
      item0.setProductName("");
      assertNull(item0.getAsin());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getQuantity();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Item item0 = new Item();
      // Undeclared exception!
      try { 
        item0.getCleanPrice();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.kencochrane.a4j.util.a4jUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getCatalog();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Item item0 = new Item();
      item0.setCatalog((String) null);
      assertNull(item0.getMerchantSku());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Item item0 = new Item();
      item0.setOurPrice((String) null);
      assertNull(item0.getMerchantSku());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.toString();
      assertEquals("Asin = null\nName = null\nquantity = null\n", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getAsin();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getExchangeId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Item item0 = new Item();
      item0.setExchangeId("&i&p}*Nymv");
      assertNull(item0.getAsin());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getProductName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getListPrice();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getItemId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getOurPrice();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Item item0 = new Item();
      item0.setItemId("");
      assertNull(item0.getOurPrice());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Item item0 = new Item();
      item0.setMerchantSku((String) null);
      assertNull(item0.getExchangeId());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Item item0 = new Item();
      item0.setListPrice((String) null);
      assertNull(item0.getOurPrice());
  }
}
