/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:56:43 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.ListingProductDetails;
import net.kencochrane.a4j.beans.ListingProductInfo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ListingProductInfo_ESTest extends ListingProductInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ListingProductInfo listingProductInfo0 = new ListingProductInfo();
      ListingProductDetails[] listingProductDetailsArray0 = new ListingProductDetails[5];
      listingProductInfo0.setListingProductDetails(listingProductDetailsArray0);
      assertEquals(5, listingProductDetailsArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ListingProductInfo listingProductInfo0 = new ListingProductInfo();
      ArrayList arrayList0 = listingProductInfo0.getListingProductDetailsArray();
      assertNull(arrayList0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ListingProductInfo listingProductInfo0 = new ListingProductInfo();
      // Undeclared exception!
      try { 
        listingProductInfo0.getListingProductDetails();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.kencochrane.a4j.beans.ListingProductInfo", e);
      }
  }
}
