/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:57:52 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.Lists;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Lists_ESTest extends Lists_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Lists lists0 = new Lists();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "";
      lists0.setListId(stringArray0);
      String string0 = lists0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Lists lists0 = new Lists();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      lists0.lists = arrayList0;
      String string0 = lists0.toString();
      assertEquals("lists is null or size 0 \n", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Lists lists0 = new Lists();
      String string0 = lists0.toString();
      assertEquals("lists is null or size 0 \n", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Lists lists0 = new Lists();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      lists0.lists = arrayList0;
      // Undeclared exception!
      try { 
        lists0.getListId(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Lists lists0 = new Lists();
      String[] stringArray0 = new String[1];
      lists0.setListId(stringArray0);
      String string0 = lists0.getListId(0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Lists lists0 = new Lists();
      String[] stringArray0 = new String[1];
      lists0.setListId(stringArray0);
      String[] stringArray1 = lists0.getListId();
      assertEquals(1, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Lists lists0 = new Lists();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      lists0.lists = arrayList0;
      String[] stringArray0 = lists0.getListId();
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Lists lists0 = new Lists();
      ArrayList arrayList0 = lists0.getListsArray();
      assertNull(arrayList0);
  }
}
