/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:56:36 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import net.kencochrane.a4j.beans.ListingProductDetails;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ListingProductDetails_ESTest extends ListingProductDetails_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeSellerNickname();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeEndDate();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeOfferingType("");
      assertNull(listingProductDetails0.getExchangeTitle());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeStatus("");
      assertNull(listingProductDetails0.getExchangeSellerId());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangePrice();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeOfferingType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeStartDate("Ex Price ");
      assertNull(listingProductDetails0.getListingId());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeQuantity();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeId("");
      assertNull(listingProductDetails0.getExchangeEndDate());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeQuantity("");
      assertNull(listingProductDetails0.getExchangeSellerState());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getListingId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeSellerId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeSellerCountry();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeQuantityAllocated((String) null);
      assertNull(listingProductDetails0.getExchangeOfferingType());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.toString();
      assertEquals(" ----------- <br />\nASIN null<br />\nAvail null<br />\nCondition Type null<br />\nEndDate null<br />\nFeatured Cat null<br />\nEx ID null<br />\nOffer Type null<br />\nEx Price null<br />\nEx Quant null<br />\nQuantity Allocated null<br />\nSeller Country null<br />\nSeller Id null<br />\nSeller Nickname null<br />\nSeller Rating null<br />\nSeller State null<br />\nStart date null<br />\nStatus null<br />\nTitle null<br />\n ----------- <br />\n", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeConditionType("z<[=]`=Gif[0");
      assertNull(listingProductDetails0.getExchangeId());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeStatus();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeAsin();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeAvailability("=RVP?>Qs3 c/ /rc +7");
      assertNull(listingProductDetails0.getExchangeSellerId());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeConditionType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeSellerRating((String) null);
      assertNull(listingProductDetails0.getExchangeSellerNickname());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeStartDate();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeEndDate("cV-+& eDO;)u`Ace;g");
      assertNull(listingProductDetails0.getExchangeStatus());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangePrice("");
      assertNull(listingProductDetails0.getExchangeSellerCountry());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeSellerRating();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeAvailability();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeSellerNickname("}Y9C*9sORmF'8");
      assertNull(listingProductDetails0.getExchangeEndDate());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeSellerId("$loF9NhXY");
      assertNull(listingProductDetails0.getExchangeSellerState());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeFeaturedCategory();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeSellerState("Condition Type ");
      assertEquals("Condition Type ", listingProductDetails0.getExchangeSellerState());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeQuantityAllocated();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeSellerCountry((String) null);
      assertNull(listingProductDetails0.getExchangeAsin());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      String string0 = listingProductDetails0.getExchangeSellerState();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeFeaturedCategory("Bz>S\fpjc4o_#RS+SdE");
      assertNull(listingProductDetails0.getExchangeTitle());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeAsin("91*F/ l{e.'HV[/TA");
      assertNull(listingProductDetails0.getExchangeSellerNickname());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setListingId("");
      assertNull(listingProductDetails0.getExchangeSellerCountry());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      ListingProductDetails listingProductDetails0 = new ListingProductDetails();
      listingProductDetails0.setExchangeTitle("_+'KxFc");
      assertNull(listingProductDetails0.getExchangeSellerState());
  }
}
