/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:58:03 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import net.kencochrane.a4j.beans.MiniProduct;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MiniProduct_ESTest extends MiniProduct_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MiniProduct miniProduct0 = new MiniProduct();
      miniProduct0.setAsin("");
      assertEquals("", miniProduct0.getAsin());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MiniProduct miniProduct0 = new MiniProduct();
      String string0 = miniProduct0.getManufacturer();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MiniProduct miniProduct0 = new MiniProduct();
      miniProduct0.setManufacturer("Ic18zh");
      assertNull(miniProduct0.getAsin());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MiniProduct miniProduct0 = new MiniProduct();
      String string0 = miniProduct0.getProductUrl();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MiniProduct miniProduct0 = new MiniProduct();
      String string0 = miniProduct0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MiniProduct miniProduct0 = new MiniProduct();
      String string0 = miniProduct0.getAsin();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MiniProduct miniProduct0 = new MiniProduct();
      miniProduct0.setPrice((String) null);
      assertNull(miniProduct0.getProductUrl());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MiniProduct miniProduct0 = new MiniProduct();
      String string0 = miniProduct0.toString();
      assertEquals("null \n null \n null \n null \n null", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MiniProduct miniProduct0 = new MiniProduct();
      String string0 = miniProduct0.getImageURL();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MiniProduct miniProduct0 = new MiniProduct();
      miniProduct0.setName((String) null);
      assertNull(miniProduct0.getAsin());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MiniProduct miniProduct0 = new MiniProduct();
      miniProduct0.setImageURL((String) null);
      assertNull(miniProduct0.getAsin());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MiniProduct miniProduct0 = new MiniProduct();
      miniProduct0.setProductUrl("");
      assertNull(miniProduct0.getImageURL());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MiniProduct miniProduct0 = new MiniProduct();
      String string0 = miniProduct0.getPrice();
      assertNull(string0);
  }
}
