/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:58:12 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.Mode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Mode_ESTest extends Mode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Mode mode0 = new Mode();
      mode0.setDefaultNode((String) null);
      assertNull(mode0.getDefaultNode());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Mode mode0 = new Mode();
      mode0.setModeName((String) null);
      assertNull(mode0.getModeName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Mode mode0 = new Mode();
      String string0 = mode0.getModeName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Mode mode0 = new Mode();
      ArrayList arrayList0 = mode0.getSubNodes();
      mode0.setSubNodes(arrayList0);
      assertNull(mode0.getDefaultNode());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Mode mode0 = new Mode();
      String string0 = mode0.getDefaultNode();
      assertNull(string0);
  }
}
