/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:58:23 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.Mode;
import net.kencochrane.a4j.beans.ModeList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ModeList_ESTest extends ModeList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ModeList modeList0 = new ModeList();
      Mode mode0 = new Mode();
      mode0.setModeName("V-p>|HF");
      modeList0.addMode(mode0);
      Mode mode1 = modeList0.getMode("V-p>|HF");
      assertEquals("V-p>|HF", mode1.getModeName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ModeList modeList0 = new ModeList();
      Mode mode0 = new Mode();
      mode0.setModeName("H");
      modeList0.addMode(mode0);
      Mode mode1 = modeList0.getMode("\"%],p;5)Zm2=*}7i");
      assertNull(mode1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ModeList modeList0 = new ModeList();
      modeList0.modes = null;
      Mode mode0 = modeList0.getMode("");
      assertNull(mode0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ModeList modeList0 = new ModeList();
      Mode mode0 = modeList0.getMode("1<,6QEOW^n%3!J`");
      modeList0.addMode(mode0);
      // Undeclared exception!
      try { 
        modeList0.getMode("V-p>|HF");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.kencochrane.a4j.beans.ModeList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ModeList modeList0 = new ModeList();
      ArrayList arrayList0 = modeList0.getAllModes();
      assertTrue(arrayList0.isEmpty());
  }
}
