/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:59:32 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.Platforms;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Platforms_ESTest extends Platforms_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Platforms platforms0 = new Platforms();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "K";
      platforms0.setPlatform(stringArray0);
      String string0 = platforms0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Platforms platforms0 = new Platforms();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      platforms0.platform = arrayList0;
      String string0 = platforms0.toString();
      assertEquals("Platforms is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Platforms platforms0 = new Platforms();
      String string0 = platforms0.toString();
      assertEquals("Platforms is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Platforms platforms0 = new Platforms();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      platforms0.platform = arrayList0;
      // Undeclared exception!
      try { 
        platforms0.getPlatform(178);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 178, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Platforms platforms0 = new Platforms();
      String[] stringArray0 = new String[1];
      platforms0.setPlatform(stringArray0);
      String string0 = platforms0.getPlatform((-1855));
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Platforms platforms0 = new Platforms();
      String[] stringArray0 = new String[1];
      platforms0.setPlatform(stringArray0);
      String[] stringArray1 = platforms0.getPlatform();
      assertEquals(1, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Platforms platforms0 = new Platforms();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      platforms0.platform = arrayList0;
      String[] stringArray0 = platforms0.getPlatform();
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Platforms platforms0 = new Platforms();
      ArrayList arrayList0 = platforms0.getPlatformsArray();
      assertNull(arrayList0);
  }
}
