/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:00:56 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import net.kencochrane.a4j.beans.Accessories;
import net.kencochrane.a4j.beans.Artists;
import net.kencochrane.a4j.beans.Authors;
import net.kencochrane.a4j.beans.BrowseList;
import net.kencochrane.a4j.beans.Directors;
import net.kencochrane.a4j.beans.Features;
import net.kencochrane.a4j.beans.Lists;
import net.kencochrane.a4j.beans.Platforms;
import net.kencochrane.a4j.beans.ProductDetails;
import net.kencochrane.a4j.beans.Reviews;
import net.kencochrane.a4j.beans.SimilarProducts;
import net.kencochrane.a4j.beans.Starring;
import net.kencochrane.a4j.beans.ThirdPartyProductInfo;
import net.kencochrane.a4j.beans.Tracks;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProductDetails_ESTest extends ProductDetails_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      Reviews reviews0 = productDetails0.reviews;
      reviews0.setAvgCustomerRating("");
      String string0 = productDetails0.getRecommendation();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      String string0 = productDetails0.getRecommendation();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.reviews = null;
      String string0 = productDetails0.getRecommendation();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      String string0 = productDetails0.getRatingsImgURL();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setOurPrice("");
      productDetails0.setListPrice("");
      String string0 = productDetails0.getSavings();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      String string0 = productDetails0.getSavings();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      Starring starring0 = new Starring();
      productDetails0.setStarring(starring0);
      assertNull(productDetails0.getImageUrlLarge());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setRefurbishedCount("$");
      assertNull(productDetails0.getAsin());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setEncoding((String) null);
      assertNull(productDetails0.getReadingLevel());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setCatalog("7CJ`,N)B+\"");
      assertNull(productDetails0.getReadingLevel());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setAsin("");
      assertNull(productDetails0.getDistributor());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      SimilarProducts similarProducts0 = productDetails0.similarProducts;
      productDetails0.setSimilarProducts(similarProducts0);
      assertNull(productDetails0.getMpn());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setAvailability("ZrQ");
      assertNull(productDetails0.getDistributor());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setProductName("$");
      assertNull(productDetails0.getImageUrlSmall());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      BrowseList browseList0 = new BrowseList();
      productDetails0.setBrowseList(browseList0);
      assertNull(productDetails0.getImageUrlLarge());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setUsedCount("");
      assertNull(productDetails0.getImageUrlSmall());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setReviews((Reviews) null);
      String string0 = productDetails0.getRatingsImgURL();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setArtists((Artists) null);
      assertNull(productDetails0.getMedia());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      Authors authors0 = new Authors();
      productDetails0.setAuthors(authors0);
      assertNull(productDetails0.getThirdPartyNewPrice());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setThirdPartyNewPrice("wvkY@1U");
      assertNull(productDetails0.getIsbn());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setMpaaRating("@uZy-RYm9z=|");
      assertNull(productDetails0.getImageUrlMedium());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setRefurbishedPrice("");
      assertNull(productDetails0.getImageUrlSmall());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setListPrice("U\",78CU;2Ws");
      String string0 = productDetails0.getSavings();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setImageUrlSmall("");
      assertNull(productDetails0.getIsbn());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setImageUrlLarge("# of Actors = ");
      assertNull(productDetails0.getThirdPartyNewPrice());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setCollectiblePrice("hEvV3;Eks9c]XmWN");
      assertNull(productDetails0.getRefurbishedCount());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setMedia(">lt=");
      assertNull(productDetails0.getRefurbishedCount());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setReadingLevel("# of Directors = ");
      assertNull(productDetails0.getNumberOfItems());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setDistributor("7CJ`,N)B+\"");
      assertNull(productDetails0.getProductName());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setLists((Lists) null);
      assertNull(productDetails0.getReadingLevel());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      Tracks tracks0 = productDetails0.tracks;
      productDetails0.setTracks(tracks0);
      assertNull(productDetails0.getMpn());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setEsrbRating((String) null);
      assertNull(productDetails0.getRefurbishedCount());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      Accessories accessories0 = productDetails0.accessories;
      productDetails0.setAccessories(accessories0);
      assertNull(productDetails0.getImageUrlMedium());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setPlatforms((Platforms) null);
      assertNull(productDetails0.getAgeGroup());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      Directors directors0 = productDetails0.getDirectors();
      productDetails0.setDirectors(directors0);
      assertNull(productDetails0.getCollectibleCount());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setImageUrlMedium("");
      assertNull(productDetails0.getDistributor());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setUsedPrice("");
      assertNull(productDetails0.getCatalog());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setManufacturer("");
      assertNull(productDetails0.getCatalog());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setUpc("lists is null or size 0 \n");
      assertNull(productDetails0.getCollectibleCount());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setAgeGroup((String) null);
      assertNull(productDetails0.getMpaaRating());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setMpn((String) null);
      assertNull(productDetails0.getUsedPrice());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setNumberOfItems("7CJ`,N)B+\"");
      assertNull(productDetails0.getDistributor());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setNumberOfOfferings(",@D%rU?Bi");
      assertNull(productDetails0.getNumberOfItems());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setThirdPartyNewCount((String) null);
      assertNull(productDetails0.getDistributor());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setUrl("");
      assertNull(productDetails0.getUsedCount());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setCollectibleCount("");
      assertNull(productDetails0.getProductName());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      ThirdPartyProductInfo thirdPartyProductInfo0 = productDetails0.thirdPartyProductInfo;
      productDetails0.setThirdPartyProductInfo(thirdPartyProductInfo0);
      assertNull(productDetails0.getStatus());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      Features features0 = productDetails0.getFeatures();
      productDetails0.setFeatures(features0);
      assertNull(productDetails0.getEncoding());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setStatus("Medium Image - ");
      assertNull(productDetails0.getIsbn());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      String string0 = productDetails0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      Reviews reviews0 = productDetails0.getReviews();
      reviews0.setAvgCustomerRating("");
      String string0 = productDetails0.getRatingsImgURL();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setSalesRank("");
      assertNull(productDetails0.getCatalog());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setTheatricalReleaseDate("<yC(?0>87S");
      assertNull(productDetails0.getCatalog());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setIsbn("Refurbished Count - ");
      assertNull(productDetails0.getReadingLevel());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      ProductDetails productDetails0 = new ProductDetails();
      productDetails0.setReleaseDate("");
      assertNull(productDetails0.getThirdPartyNewPrice());
  }
}
