/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:01:24 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import net.kencochrane.a4j.beans.ProductInfo;
import net.kencochrane.a4j.beans.ProductLine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProductLine_ESTest extends ProductLine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProductLine productLine0 = new ProductLine();
      ProductInfo productInfo0 = new ProductInfo();
      productLine0.setProductInfo(productInfo0);
      assertNull(productLine0.getMode());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ProductLine productLine0 = new ProductLine();
      // Undeclared exception!
      try { 
        productLine0.printProductList();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.kencochrane.a4j.beans.ProductLine", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ProductLine productLine0 = new ProductLine();
      productLine0.setMode("87@\"X{/X6");
      assertEquals("87@\"X{/X6", productLine0.getMode());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ProductLine productLine0 = new ProductLine();
      String string0 = productLine0.toString();
      assertEquals("Mode = null\nnull\n", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ProductLine productLine0 = new ProductLine();
      ProductInfo productInfo0 = productLine0.getProductInfo();
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ProductLine productLine0 = new ProductLine();
      String string0 = productLine0.getMode();
      assertNull(string0);
  }
}
