/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:01:12 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.ProductDetails;
import net.kencochrane.a4j.beans.ProductInfo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProductInfo_ESTest extends ProductInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProductInfo productInfo0 = new ProductInfo();
      ProductDetails[] productDetailsArray0 = new ProductDetails[1];
      ProductDetails productDetails0 = new ProductDetails();
      productDetailsArray0[0] = productDetails0;
      productInfo0.setDetails(productDetailsArray0);
      String string0 = productInfo0.printProductList();
      assertEquals("Total results = null\nTotal pages = null\n< 0 > null : null - null\n# of products = 1\n", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ProductInfo productInfo0 = new ProductInfo();
      String string0 = productInfo0.printProductList();
      assertEquals("Total results = null\nTotal pages = null\nproducts is null \n", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ProductInfo productInfo0 = new ProductInfo();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      Integer integer0 = new Integer((-1084));
      arrayList0.add(integer0);
      productInfo0.products = arrayList0;
      // Undeclared exception!
      try { 
        productInfo0.toString();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Integer cannot be cast to net.kencochrane.a4j.beans.ProductDetails
         //
         verifyException("net.kencochrane.a4j.beans.ProductInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ProductInfo productInfo0 = new ProductInfo();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      productInfo0.products = arrayList0;
      String string0 = productInfo0.toString();
      assertEquals("Total results = null\nTotal pages = null\n# of products = 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ProductInfo productInfo0 = new ProductInfo();
      // Undeclared exception!
      try { 
        productInfo0.getDetails();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.kencochrane.a4j.beans.ProductInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ProductInfo productInfo0 = new ProductInfo();
      productInfo0.setTotalResults("");
      assertNull(productInfo0.getListName());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ProductInfo productInfo0 = new ProductInfo();
      String string0 = productInfo0.getListName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ProductInfo productInfo0 = new ProductInfo();
      String string0 = productInfo0.toString();
      assertEquals("Total results = null\nTotal pages = null\nproducts is null \n", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ProductInfo productInfo0 = new ProductInfo();
      productInfo0.setTotalPages("");
      assertEquals("", productInfo0.getTotalPages());
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      ProductInfo productInfo0 = new ProductInfo();
      productInfo0.setListName((String) null);
      assertNull(productInfo0.getTotalPages());
  }
}
