/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:02:31 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.MiniProduct;
import net.kencochrane.a4j.beans.RecentlyViewed;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RecentlyViewed_ESTest extends RecentlyViewed_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RecentlyViewed recentlyViewed0 = new RecentlyViewed();
      MiniProduct miniProduct0 = new MiniProduct();
      miniProduct0.setAsin("");
      recentlyViewed0.addProduct(miniProduct0);
      boolean boolean0 = recentlyViewed0.isInList("3W");
      assertEquals(1, recentlyViewed0.getNumProducts());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RecentlyViewed recentlyViewed0 = new RecentlyViewed();
      MiniProduct miniProduct0 = new MiniProduct();
      recentlyViewed0.addProduct(miniProduct0);
      boolean boolean0 = recentlyViewed0.isInList("3W");
      assertEquals(1, recentlyViewed0.getNumProducts());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RecentlyViewed recentlyViewed0 = new RecentlyViewed();
      MiniProduct miniProduct0 = new MiniProduct();
      recentlyViewed0.addProduct(miniProduct0);
      miniProduct0.asin = "D _e,|WYj)vNOn3D";
      recentlyViewed0.addProduct(miniProduct0);
      assertEquals(1, recentlyViewed0.getNumProducts());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RecentlyViewed recentlyViewed0 = new RecentlyViewed();
      recentlyViewed0.addProduct((MiniProduct) null);
      assertEquals(0, recentlyViewed0.getNumProducts());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RecentlyViewed recentlyViewed0 = new RecentlyViewed();
      int int0 = recentlyViewed0.getNumProducts();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RecentlyViewed recentlyViewed0 = new RecentlyViewed();
      ArrayList arrayList0 = recentlyViewed0.getProducts();
      assertEquals(0, arrayList0.size());
  }
}
