/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:02:42 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import net.kencochrane.a4j.beans.CustomerReview;
import net.kencochrane.a4j.beans.Reviews;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Reviews_ESTest extends Reviews_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Reviews reviews0 = new Reviews();
      CustomerReview[] customerReviewArray0 = new CustomerReview[3];
      reviews0.setCustomerReview(customerReviewArray0);
      String string0 = reviews0.toString();
      assertEquals("null\nnull\nnull\nnull\nnull\n# of reviews = 3", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Reviews reviews0 = new Reviews();
      // Undeclared exception!
      try { 
        reviews0.getCustomerReview();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.kencochrane.a4j.beans.Reviews", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Reviews reviews0 = new Reviews();
      String string0 = "czzy\\u'oele9m8o$#{X";
      reviews0.setAvgCustomerRating(string0);
      assertEquals("czzy\\u'oele9m8o$#{X", reviews0.getAvgCustomerRating());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Reviews reviews0 = new Reviews();
      reviews0.setTotalCustomerReviews((String) null);
      assertNull(reviews0.getTotalCustomerReviews());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Reviews reviews0 = new Reviews();
      String string0 = reviews0.toString();
      assertEquals("null\nnull\nreviews is null ", string0);
  }
}
