/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:03:25 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import net.kencochrane.a4j.beans.ListingProductInfo;
import net.kencochrane.a4j.beans.SellerSearchDetails;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SellerSearchDetails_ESTest extends SellerSearchDetails_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SellerSearchDetails sellerSearchDetails0 = new SellerSearchDetails();
      sellerSearchDetails0.setStoreId("Mf");
      assertNull(sellerSearchDetails0.getSellerNickname());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SellerSearchDetails sellerSearchDetails0 = new SellerSearchDetails();
      ListingProductInfo listingProductInfo0 = new ListingProductInfo();
      sellerSearchDetails0.setListingProductInfo(listingProductInfo0);
      assertNull(sellerSearchDetails0.getStoreId());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SellerSearchDetails sellerSearchDetails0 = new SellerSearchDetails();
      String string0 = sellerSearchDetails0.getStoreName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SellerSearchDetails sellerSearchDetails0 = new SellerSearchDetails();
      String string0 = sellerSearchDetails0.getNumberOfOpenListings();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SellerSearchDetails sellerSearchDetails0 = new SellerSearchDetails();
      String string0 = sellerSearchDetails0.getSellerNickname();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SellerSearchDetails sellerSearchDetails0 = new SellerSearchDetails();
      ListingProductInfo listingProductInfo0 = sellerSearchDetails0.getListingProductInfo();
      assertNull(listingProductInfo0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SellerSearchDetails sellerSearchDetails0 = new SellerSearchDetails();
      sellerSearchDetails0.setNumberOfOpenListings((String) null);
      assertNull(sellerSearchDetails0.getStoreId());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SellerSearchDetails sellerSearchDetails0 = new SellerSearchDetails();
      sellerSearchDetails0.setStoreName("net.kencochrane.a4j.beans.SellerSearchDetails");
      assertEquals("net.kencochrane.a4j.beans.SellerSearchDetails", sellerSearchDetails0.getStoreName());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      SellerSearchDetails sellerSearchDetails0 = new SellerSearchDetails();
      String string0 = sellerSearchDetails0.getStoreId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      SellerSearchDetails sellerSearchDetails0 = new SellerSearchDetails();
      sellerSearchDetails0.setSellerNickname((String) null);
      assertNull(sellerSearchDetails0.getStoreName());
  }
}
