/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:02:57 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import net.kencochrane.a4j.beans.SellerProfile;
import net.kencochrane.a4j.beans.SellerProfileDetails;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SellerProfile_ESTest extends SellerProfile_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SellerProfile sellerProfile0 = new SellerProfile();
      SellerProfileDetails sellerProfileDetails0 = sellerProfile0.getSellerProfileDetails();
      assertNull(sellerProfileDetails0.getStoreId());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SellerProfile sellerProfile0 = new SellerProfile();
      String string0 = sellerProfile0.toString();
      assertEquals("NickName = null\nOverallRating = null\n# of feedbacks = null\n# of Canceled Auctions = null\nStoreId = null\nStoreName = null\nFeedBack = \nfeedbacks is null \n\n", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SellerProfile sellerProfile0 = new SellerProfile();
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      sellerProfile0.setSellerProfileDetails(sellerProfileDetails0);
      assertNull(sellerProfileDetails0.getSellerNickname());
  }
}
