/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:03:08 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import net.kencochrane.a4j.beans.SellerFeedback;
import net.kencochrane.a4j.beans.SellerProfileDetails;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SellerProfileDetails_ESTest extends SellerProfileDetails_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      String string0 = sellerProfileDetails0.getSellerNickname();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      String string0 = sellerProfileDetails0.toString();
      assertEquals("NickName = null\nOverallRating = null\n# of feedbacks = null\n# of Canceled Auctions = null\nStoreId = null\nStoreName = null\nFeedBack = \nfeedbacks is null \n", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      String string0 = sellerProfileDetails0.getStoreName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      sellerProfileDetails0.setOverallFeedbackRating("");
      assertEquals("", sellerProfileDetails0.getOverallFeedbackRating());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      sellerProfileDetails0.setStoreName((String) null);
      assertNull(sellerProfileDetails0.getStoreId());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      sellerProfileDetails0.setSellerNickname((String) null);
      assertNull(sellerProfileDetails0.getNumberOfFeedback());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      String string0 = sellerProfileDetails0.getNumberOfFeedback();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      SellerFeedback sellerFeedback0 = sellerProfileDetails0.getSellerFeedBack();
      sellerProfileDetails0.setSellerFeedBack(sellerFeedback0);
      assertNull(sellerProfileDetails0.getOverallFeedbackRating());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      String string0 = sellerProfileDetails0.getNumberofCanceledAuctions();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      String string0 = sellerProfileDetails0.getOverallFeedbackRating();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      sellerProfileDetails0.setNumberOfFeedback("");
      assertNull(sellerProfileDetails0.getNumberofCanceledAuctions());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      String string0 = sellerProfileDetails0.getStoreId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      sellerProfileDetails0.setStoreId((String) null);
      assertNull(sellerProfileDetails0.getNumberofCanceledAuctions());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SellerProfileDetails sellerProfileDetails0 = new SellerProfileDetails();
      sellerProfileDetails0.setNumberofCanceledAuctions("NickName = null\nOverallRating = null\n# of feedbacks = null\n# of Canceled Auctions = null\nStoreId = null\nStoreName = null\nFeedBack = \nfeedbacks is null \n");
      assertEquals("NickName = null\nOverallRating = null\n# of feedbacks = null\n# of Canceled Auctions = null\nStoreId = null\nStoreName = null\nFeedBack = \nfeedbacks is null \n", sellerProfileDetails0.getNumberofCanceledAuctions());
  }
}
