/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:03:16 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.SellerSearch;
import net.kencochrane.a4j.beans.SellerSearchDetails;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SellerSearch_ESTest extends SellerSearch_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SellerSearch sellerSearch0 = new SellerSearch();
      SellerSearchDetails[] sellerSearchDetailsArray0 = new SellerSearchDetails[7];
      sellerSearch0.setSellerSearchDetails(sellerSearchDetailsArray0);
      assertEquals(7, sellerSearchDetailsArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SellerSearch sellerSearch0 = new SellerSearch();
      ArrayList arrayList0 = sellerSearch0.getSellerSearchDetailsArray();
      assertNull(arrayList0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SellerSearch sellerSearch0 = new SellerSearch();
      // Undeclared exception!
      try { 
        sellerSearch0.getSellerSearchDetails();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.kencochrane.a4j.beans.SellerSearch", e);
      }
  }
}
