/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:04:44 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import net.kencochrane.a4j.beans.ShoppingCart;
import net.kencochrane.a4j.beans.ShoppingCartResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ShoppingCartResponse_ESTest extends ShoppingCartResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ShoppingCartResponse shoppingCartResponse0 = new ShoppingCartResponse();
      ShoppingCart shoppingCart0 = shoppingCartResponse0.getShoppingCart();
      shoppingCartResponse0.setShoppingCart(shoppingCart0);
  }
}
