/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:04:38 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import net.kencochrane.a4j.beans.Item;
import net.kencochrane.a4j.beans.Items;
import net.kencochrane.a4j.beans.ShoppingCart;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ShoppingCart_ESTest extends ShoppingCart_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      Items items0 = new Items();
      Item[] itemArray0 = new Item[2];
      Item item0 = new Item();
      itemArray0[1] = item0;
      items0.setItem(itemArray0);
      shoppingCart0.setItems(items0);
      shoppingCart0.getNumItems();
      assertEquals("1", shoppingCart0.getNumItems());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      Items items0 = new Items();
      items0.items = null;
      shoppingCart0.setItems(items0);
      String string0 = shoppingCart0.getNumItems();
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      Items items0 = new Items();
      shoppingCart0.setItems(items0);
      String string0 = shoppingCart0.getNumItems();
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      String string0 = shoppingCart0.getNumItems();
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      Items items0 = new Items();
      Item[] itemArray0 = new Item[3];
      items0.setItem(itemArray0);
      shoppingCart0.setItems(items0);
      // Undeclared exception!
      try { 
        shoppingCart0.getItem("'S*Z|3IQ#vKy'-mAjt");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.kencochrane.a4j.beans.ShoppingCart", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      Items items0 = new Items();
      items0.items = null;
      shoppingCart0.setItems(items0);
      Item item0 = shoppingCart0.getItem("C_T5@eG(PczC5");
      assertNull(item0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      Items items0 = new Items();
      shoppingCart0.setItems(items0);
      Item item0 = shoppingCart0.getItem("C_T5@eG(PczC5");
      assertNull(item0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      Item item0 = shoppingCart0.getItem("");
      assertNull(item0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      Items items0 = new Items();
      Item[] itemArray0 = new Item[1];
      shoppingCart0.setItems(items0);
      Item item0 = new Item();
      itemArray0[0] = item0;
      items0.setItem(itemArray0);
      shoppingCart0.getTotalCartCost();
      assertEquals("1", shoppingCart0.getNumItems());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      Items items0 = new Items();
      items0.items = null;
      shoppingCart0.setItems(items0);
      String string0 = shoppingCart0.getTotalCartCost();
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      String string0 = shoppingCart0.getTotalCartCost();
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      shoppingCart0.setCartId("<lLG{Z#a&-z");
      assertEquals("0", shoppingCart0.getNumItems());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      Items items0 = shoppingCart0.getItems();
      assertNull(items0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      String string0 = shoppingCart0.getCartId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      shoppingCart0.setPurchaseURL("");
      assertNull(shoppingCart0.getCartId());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      String string0 = shoppingCart0.toString();
      assertEquals("HMAC = null\nPurchase URL = null\nCartId = null\nitems = null\n", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      String string0 = shoppingCart0.getHMAC();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      shoppingCart0.setHMAC("net.kencochrane.a4j.beans.Item");
      assertNull(shoppingCart0.getPurchaseURL());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      Items items0 = new Items();
      shoppingCart0.setItems(items0);
      String string0 = shoppingCart0.getTotalCartCost();
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ShoppingCart shoppingCart0 = new ShoppingCart();
      String string0 = shoppingCart0.getPurchaseURL();
      assertNull(string0);
  }
}
