/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:05:53 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.SimilarProducts;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SimilarProducts_ESTest extends SimilarProducts_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimilarProducts similarProducts0 = new SimilarProducts();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "";
      similarProducts0.setProduct(stringArray0);
      String string0 = similarProducts0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimilarProducts similarProducts0 = new SimilarProducts();
      String[] stringArray0 = new String[0];
      similarProducts0.setProduct(stringArray0);
      String string0 = similarProducts0.toString();
      assertEquals("Similar Products is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SimilarProducts similarProducts0 = new SimilarProducts();
      String string0 = similarProducts0.toString();
      assertEquals("Similar Products is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SimilarProducts similarProducts0 = new SimilarProducts();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      similarProducts0.simProducts = arrayList0;
      // Undeclared exception!
      try { 
        similarProducts0.getProduct(3543);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 3543, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SimilarProducts similarProducts0 = new SimilarProducts();
      String[] stringArray0 = new String[1];
      similarProducts0.setProduct(stringArray0);
      String string0 = similarProducts0.getProduct(0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SimilarProducts similarProducts0 = new SimilarProducts();
      String[] stringArray0 = new String[1];
      similarProducts0.setProduct(stringArray0);
      String[] stringArray1 = similarProducts0.getProduct();
      assertEquals(1, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SimilarProducts similarProducts0 = new SimilarProducts();
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      similarProducts0.simProducts = arrayList0;
      String[] stringArray0 = similarProducts0.getProduct();
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SimilarProducts similarProducts0 = new SimilarProducts();
      ArrayList arrayList0 = similarProducts0.getProductsArray();
      assertNull(arrayList0);
  }
}
