/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:07:05 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import net.kencochrane.a4j.beans.ThirdPartyProductDetails;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ThirdPartyProductDetails_ESTest extends ThirdPartyProductDetails_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ThirdPartyProductDetails thirdPartyProductDetails0 = new ThirdPartyProductDetails();
      thirdPartyProductDetails0.setSellerId((String) null);
      assertNull(thirdPartyProductDetails0.getExchangeId());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ThirdPartyProductDetails thirdPartyProductDetails0 = new ThirdPartyProductDetails();
      String string0 = thirdPartyProductDetails0.getSellerRating();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ThirdPartyProductDetails thirdPartyProductDetails0 = new ThirdPartyProductDetails();
      thirdPartyProductDetails0.setShipComments("[H/5:e&)e06:fZ");
      assertNull(thirdPartyProductDetails0.getConditionType());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ThirdPartyProductDetails thirdPartyProductDetails0 = new ThirdPartyProductDetails();
      thirdPartyProductDetails0.setCondition((String) null);
      assertNull(thirdPartyProductDetails0.getOfferingPrice());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ThirdPartyProductDetails thirdPartyProductDetails0 = new ThirdPartyProductDetails();
      thirdPartyProductDetails0.setSellerNickname("");
      assertNull(thirdPartyProductDetails0.getExchangeId());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ThirdPartyProductDetails thirdPartyProductDetails0 = new ThirdPartyProductDetails();
      String string0 = thirdPartyProductDetails0.toString();
      assertEquals("------------------- \nSellerId = null\nSellerNickName = null\nExchangeID = null\nPrice =  null\nCondition = null\nCondition Type = null\nExchange Availability = null\nCounty = null\nState = null\nComments = null\n------------------- \n", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ThirdPartyProductDetails thirdPartyProductDetails0 = new ThirdPartyProductDetails();
      thirdPartyProductDetails0.setOfferingPrice((String) null);
      assertNull(thirdPartyProductDetails0.getConditionType());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ThirdPartyProductDetails thirdPartyProductDetails0 = new ThirdPartyProductDetails();
      thirdPartyProductDetails0.setSellerRating("[H/5:e&)e06:fZ");
      assertNull(thirdPartyProductDetails0.getOfferingPrice());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ThirdPartyProductDetails thirdPartyProductDetails0 = new ThirdPartyProductDetails();
      thirdPartyProductDetails0.setSellerCountry("P|oEi:RYw");
      assertNull(thirdPartyProductDetails0.getSellerRating());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ThirdPartyProductDetails thirdPartyProductDetails0 = new ThirdPartyProductDetails();
      thirdPartyProductDetails0.setConditionType((String) null);
      assertNull(thirdPartyProductDetails0.getConditionType());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ThirdPartyProductDetails thirdPartyProductDetails0 = new ThirdPartyProductDetails();
      thirdPartyProductDetails0.setSellerState("[H/5:e&)e06:fZ");
      assertNull(thirdPartyProductDetails0.getExchangeId());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ThirdPartyProductDetails thirdPartyProductDetails0 = new ThirdPartyProductDetails();
      thirdPartyProductDetails0.setExchangeId("Price =  ");
      assertNull(thirdPartyProductDetails0.getConditionType());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ThirdPartyProductDetails thirdPartyProductDetails0 = new ThirdPartyProductDetails();
      thirdPartyProductDetails0.setExchangeAvailability("\"(");
      assertNull(thirdPartyProductDetails0.getExchangeId());
  }
}
