/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 02:08:21 GMT 2023
 */

package net.kencochrane.a4j.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import net.kencochrane.a4j.beans.Tracks;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Tracks_ESTest extends Tracks_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Tracks tracks0 = new Tracks();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "";
      tracks0.setTrack(stringArray0);
      String string0 = tracks0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Tracks tracks0 = new Tracks();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      tracks0.tracks = arrayList0;
      String string0 = tracks0.toString();
      assertEquals("Tracks is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Tracks tracks0 = new Tracks();
      String string0 = tracks0.toString();
      assertEquals("Tracks is null or size 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Tracks tracks0 = new Tracks();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      tracks0.tracks = arrayList0;
      // Undeclared exception!
      try { 
        tracks0.getTrack(1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Tracks tracks0 = new Tracks();
      String[] stringArray0 = new String[10];
      tracks0.setTrack(stringArray0);
      String string0 = tracks0.getTrack((-94));
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Tracks tracks0 = new Tracks();
      String[] stringArray0 = new String[1];
      tracks0.setTrack(stringArray0);
      String[] stringArray1 = tracks0.getTrack();
      assertEquals(1, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Tracks tracks0 = new Tracks();
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      tracks0.tracks = arrayList0;
      String[] stringArray0 = tracks0.getTrack();
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Tracks tracks0 = new Tracks();
      ArrayList arrayList0 = tracks0.getTracksArray();
      assertNull(arrayList0);
  }
}
