/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 28 01:45:54 GMT 2023
 */

package net.kencochrane.a4j;

import org.junit.Test;
import static org.junit.Assert.*;
import net.kencochrane.a4j.A4j;
import net.kencochrane.a4j.beans.BlendedSearch;
import net.kencochrane.a4j.beans.FullProduct;
import net.kencochrane.a4j.beans.ProductInfo;
import net.kencochrane.a4j.beans.SellerSearch;
import net.kencochrane.a4j.beans.ShoppingCart;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class A4j_ESTest extends A4j_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      A4j a4j0 = new A4j();
      FullProduct fullProduct0 = a4j0.getFullProductFromASIN("*N7", "net.kencochrane.a4j.beans.BlendedSearch", "net.kencochrane.a4j.beans.BlendedSearch");
      assertNull(fullProduct0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      A4j a4j0 = new A4j();
      ProductInfo productInfo0 = a4j0.ActorSearch("", "", "E<y.b8DazBd3");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      A4j a4j0 = new A4j();
      ProductInfo productInfo0 = a4j0.ArtistSearch("", "net.kencochrane.a4j.beans.ProductInfo", "");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      A4j a4j0 = new A4j();
      ProductInfo productInfo0 = a4j0.ManufactureSearch("", "", "r");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      A4j a4j0 = new A4j();
      ProductInfo productInfo0 = a4j0.ListmaniaSearch("cK6.?{i/UO-7!=%{");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      A4j a4j0 = new A4j();
      ProductInfo productInfo0 = a4j0.KeywordSearch("+q", ".]!=apbUaO^Rm7$y", "c~xe~`2eq", "+q");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      A4j a4j0 = new A4j();
      ShoppingCart shoppingCart0 = a4j0.modifyCart("", "net.kencochrane.a4j.beans.FullProduct", "net.kencochrane.a4j.beans.FullProduct", "");
      assertNull(shoppingCart0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      A4j a4j0 = new A4j();
      BlendedSearch blendedSearch0 = a4j0.BlendedSearch("", "net.kencochrane.a4j.beans.ProductInfo");
      assertNull(blendedSearch0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      A4j a4j0 = new A4j();
      ShoppingCart shoppingCart0 = a4j0.RemoveFromCart("x", "(^q~", "net.kencochrane.a4j.beans.BlendedSearch");
      assertNull(shoppingCart0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      A4j a4j0 = new A4j();
      ShoppingCart shoppingCart0 = a4j0.AddtoCart("net.kencochrane.a4j.A4j", "QZUXFSNY8J<wxr?M,");
      assertNull(shoppingCart0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      A4j a4j0 = new A4j();
      SellerSearch sellerSearch0 = a4j0.ThirdParty("", "", "net.kencochrane.a4j.beans.ProductInfo", "");
      assertNull(sellerSearch0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      A4j a4j0 = new A4j();
      ProductInfo productInfo0 = a4j0.UpcSearch("", "Purchase URL = ", "");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      A4j a4j0 = new A4j();
      ProductInfo productInfo0 = a4j0.DirectorSearch("", "", "");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      A4j a4j0 = new A4j();
      ShoppingCart shoppingCart0 = a4j0.addToExistingCart((String) null, "O)Vj$!7kG#C", (String) null, "");
      assertNull(shoppingCart0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      A4j a4j0 = new A4j();
      ShoppingCart shoppingCart0 = a4j0.clearCart("+R6~:\"nUXrK!tI$o", "x");
      assertNull(shoppingCart0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      A4j a4j0 = new A4j();
      ProductInfo productInfo0 = a4j0.WishListSearch("");
      assertNull(productInfo0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      A4j a4j0 = new A4j();
      ShoppingCart shoppingCart0 = a4j0.GetItemsFromCart("", "");
      assertNull(shoppingCart0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      A4j a4j0 = new A4j();
      ProductInfo productInfo0 = a4j0.AuthorSearch(".]!=apbUaO^Rm7$y", ".]!=apbUaO^Rm7$y");
      assertNull(productInfo0);
  }
}
